apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: proseed-web-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: skkuding
          repo: proseed
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "proseed-web-pr-{{number}}"
      namespace: argocd
      annotations:
        appName: "proseed-web-pr-{{number}}"
        previewURL: "https://pr-{{number}}.preview.proseednow.com"
        notifications.argoproj.io/subscribe.on-sync-succeeded.github: ""
        notifications.argoproj.io/subscribe.on-sync-failed.github: ""
        notifications.argoproj.io/subscribe.on-sync-running.github: ""
        github.com/repoURL: "https://github.com/skkuding/proseed"
        github.com/pullRequestID: "{{number}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://github.com/skkuding/proseed
          targetRevision: "{{head_sha}}"
          path: infra/k8s/web-preview
          kustomize:
            namespace: "proseed-preview-{{number}}"
            images:
              - "ghcr.io/skkuding/proseed/web:pr-{{number}}"
            patches:
              - target:
                  kind: Ingress
                  name: web-preview-ingress
                patch: |
                  - op: replace
                    path: /spec/rules/0/host
                    value: "pr-{{number}}.preview.proseednow.com"
      destination:
        server: https://kubernetes.default.svc
        namespace: "proseed-preview-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true