---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  # IAM user: lab-letsencrypt
  # TODO: provision `skkuding.dev` with Route 53 and terraform
  encryptedData:
    aws_access_key_id: AgCN/u2jlEkCMJOXx1AbaJMoOjTqcnsNniasCOkIPAg1ie2tEM8zR+nv1PdlZquSsF13i56bKFx7vKA+zoBj7TCrqLbdj8iLmRR8kzMwT/lDHN6tGa7uYzodWxn7wxioddBTmyAJmvBNmbepRjPFQhFta7z+iClECvhBmjB6EexxNMFVJ+/SyUBHzJZ1xhMYw7k5ZAPrmKggYOmaYyE0jYs2pO5OArU/jMA1i4Flmooef1AyzMfXFXKYuRp/VomOQ/gqoArSMwx9AsDtDkeFvhnvjmsqS/umNv0QRoq4eedM8ZA6fAyfwpvOUCDeZva20hLJwCKeTUWYe8H8O/s0y0pMS20pdFrKZY11Paw5czndbqUWduIocezH5ymlc9W7d2RohzmVmy/Hp4KlcBG3Uz4V+7wI0JPDZMQW4pXXC31inex5EUsEjyk0wllxQRwwsveW1z/Nzfayufdv0LJ1hMg0TwXKH0Wpr6er+Mx06p76k7mcxdPVMUjQauj/s9WB8vVCOmpGVn2cB5wFBZYFLqE8IlIjBg+UJLArS2hXllrrw/Fv/FuWg+hE7xCKDt3NSAWoN4pueFtSTQ7XaKIOyYU0hp9jdD416KSTj2H+v+aasb3t9tKCBR/Y3n+JGfsq6rjoWUyTbuO0QaHI+1hkSa1etgRHkOOvW7l4Y7zYzQyDJERA9KHhRAiYJ3xcyyAwUNZsET0DkG8jUyWZ1g8LetK3zgH5YQ==
    aws_secret_access_key: AgAsx8nUkM/yKRS0XSKVvbjacDSVhBO8Aq1+D7l9tTXGGgX8ZR8Fi07HUXicdU1jbZihp8JsZOndCrTkOUSN+oSjzJDxHEmlTfNuCLs9m8koMLQstkfyUjeobQraZHXeYz0hn4T9ha5avBLxQ7dYuotawcK0urMKsWn6BlZToBa5FVqzkW9nyMhMRzpuufJTBHpxTovFOKWgHwH9I6kkfTNWLLv9BG0dbtojL8q5vve3ldVJzwisaMEXTQUn+Z48hKSnuaLHDyTDufG9mnMPbTR+lDNAleDDo/hEkAT5+dQz35w8MMAbksVxfz8Dj8PGtHjqO65RSPRb22w4zm2ncxy6O3Arvn7DjkRwOdYNdyXX2NHsCQwtK+hWm+44rEnfwRmg3607onDj5lultHYeGrsX44ZLFKqXzZ4oP/tdLXQyl135UEN12ykWmaSdhcylZ3BeFNIsF9N2ARpCPuOl/e0N5OC0bxb1Oia4yNm9QekF7mCzw29D5X35SMMf/7vq78Lo9HCcOMcEmRTNz80pAXtcU1w4OFxcU0JYM2HjHzdGLLBq9ajT51PNUonYB5CeE+Lw0pf8JQE/TSMEo9ne0+mLek9UzrGIqJOH1/DFM2oknXNuwqtXG3Ff3z2edvJYKCGERPI4t8yP20wGR8vVp8nQMmlvhFxoGLLfj2Nxlx7WzRwtCPBl6LZoGW+aZISsL9uIHJ8oM/7AyTE19CRWwNkqgydDbzpy2ySFm0i3xb/cLZBqx1XKXNZL
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
