---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-user
  namespace: observability
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCo+gOeqg0DTaqHVQUPN3aOL5rjFezlfCUCkC7LZc71u8r4O+UzBNgKI9E8TF7MmlpHMSaekcKLTyhj8ZH2WmPqclNsDD6t2wubo5C1L9oa5LH1Tsh/SL6i+mzxgLPsw9yr8WgnLsp3JsZRl46BJokRYvPtAmf3kGa8Aie0W6JDcdaJlgPbMnt6Q4Cn14OG0WIyIeiRYNlRoANckH0f+0FVIiwkFGEaVhgcRnjVWvOpg+mvIbyldOMozUmVoKnPdyqbN3UF763KkTLq4queYOlGRurzNqxDpNz6wJpdwe47iJVw2iC+SQxsiY1D/OesympmCLABVTJ4yam1i/ZFvtxrfxEoO+MGVS/Hy0Xj3ZDrcroThEVBD2gafMqUV76MneTp0Slt3J62M2rOKUoDyYuQKEehSipo0rsqLKyyukgjuN3pDNKY1kD5an9RXFmoAnxDpGGGkFkNVA0z7mtf5wLpqB6gQTsq7PaBIMFMnvoE9fTxKcbzqzOEEEs/9xFy4weuGgxTx1upDiDJZ0i9PIoIWgBx9b8UfKbNL2qdNz5EFPDzx2CTnfynqQJJ6m8ag6BqCtzbMGKo3Qp8AmEtZh0oAslW2VygQI/ckFKAZ8ouS5/GM4Ivnppu0iyQdSfuVM9vXaTo7SXJXuvTQjC3TSV6e7JdQ7sodx7M5sqlp1OXCPYOSwizWfqZ36EZP66YY5DZ2FPvruovcgCk1Q==
    ADMIN_USER: AgC0qkslVuPNFA8RMHwQZ9nxSGQC44qvtAe4Rx43yMPL8y1O94DoiNDf5XSXcrJd8w4xStK1O5AzglOQlDxvnakVi34mdxx6LSBmv3Q6Tx1ItchuvQiob39nxhX5scbOzKz5Pw2YtGqRc3+4jLgQpYhUdPEEA4rQe7eU/NTK+WqeEBriM1PGrQ1N1Rd0Qzzi/TdwO3K3I97zsZpV3SQnqZ5kSOlq51gB5SQwpsv0d+uWUPRxeJBi+++NOncoDGdlZ2S76pS/luVGuvmYOaonjMtBk+HbM1bl9oU+GXQbrfJP/DDKiIpnqimMYTDvnbIuIFSSDDOYEqJAg4y+6T+Xvrp3NbnWuNOM1pl9BPI2mQlagirYEK3BYEObbHftc7nbNL9ytcrrWu5q3rrW5tbDHUbQClqFDMUr4kbFlxNFAMM+PmQaXyaqIp0dbE2cHazZAdvthLd2RyrcmwI7xAImgN69q7cLn+50HVzt6LhVDY2HPQKftN+9wKeEybnPrelVYrVlKPV+x5jZ4GklJij9A3p+qjlF6M4bOjJdl90Pu44cm6ZQUyJXBy0qW3nom/nQFE1QFlUW3ziqj3XjZlowP7EBXcMUCrrEDR0bdXE0yG2Da75FjRJeXxgRL1mtK4bJGmGs5C3GS2xzh+uZHiDxIyAf4sPcoYxnXzmFWhYGE84GgsAN53Uif6u7NYpOWgAh2bO+VQXVFA==
  template:
    metadata:
      name: grafana-admin-user
      namespace: observability
    type: Opaque
