---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgBgxjw10RMPMLdN4KSv9tLX/m5CyQrrBbE7V2hhlhGsVv0B9qAzLFRM67epUR7qzht2e5dy9P8iEu2refVY1B+9t1NnWcDRZvgINDUlBMzDDdgppj8ZMQMLLyO2nHuwong/D9cTT4MNtHvBGrlFd6Y+c3p2g9X1jmXczrlSvll3VUu6M3wRpbgMC9yd7HnC1I0fMNUsGAOhSFQiQDm1karOsz3xC9HSLOq5eOrBw4iylzO3k4Vd7C9VmL4r/uPibmMmkyrEIMaze5a3Goy2pcvfm8ncOCAaL0rfURgox3rlvwP+EYVvGkcxENAE71a9WeGB+NTnX8pmisLhOLR+xhiPOWC79CZpAAuf4gpj7Psq7XPH/3CNX4AB19Dsx6CTTYyKwrCLj6nhWx0CSYF1o+c34iPWO3WohzuRLeNoUCPLrx3mc2GQVRe6r5moiDsqIHBP1BrtLWyXJyaWOUoHjUhw2v+YX8cLFPLaahdj3iH9ligrS6Zo57h2cJjuRhy3SZof+E6bCwh4I1DJpGsQv4xms38Ledys/DzT6gi6rgeKSTN1R3lh2I1EZh+nxYJBGMgMx7wzbY9zoP0+0/wZEhDIn0Y1ROxeitDfoJTLCVno4zF+uSXs/z2zUrXAXge0MwOY6cCKP3ZhTJpWr5pwcVpW+HhfGnU/Fz/qjeHug9cx4OhWfHAKVYru2T+z7hEGtHAzU5mNrAnxQiuyke8S3WN+AooyKw==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgC1CPPGk1VkbD8lMvcOFRswAUHguiPKJab7Hn72LZqQ3Nv5CmLtFitKlFMTQwtp7sEKSAZOCxAsdxyk+FWA7KJAm67zpBnKCQYgisrKjMtK8vVHjcTSaGaCnb1x31W62U1nnAO0OyjhYm302Z7dbxnLDMBaUxq4dycjFqbK1C9E1YNP0zkdY6sZyWD+E47N6dQI+B9uNGYY0tfvx6zybbhVM3vk5NHvFAU1kHAWjQCNQo3JCvaWwK1oFPX1+m7w0xqT3dcpLkjdD1cZArabJt7EZhEdF3ZLojenclQaoJGeclKzFGWfhfSMQX+pMgS9TW+TTIygagE2xhF8alCWJtHw8k6CNAJcNyAwThPbXDnyFPFmgRanjvTKtIFXhWIKzgg7NZdyHxr25oxsRRlxpgGvLtTtfAJ4fNUJ3sr2ghRxKl+6RexnbdGOtWs/BOcWU9T19UDbEtJO5nHmsr61g4BwejqCEpxozAM9Yfh5dcHYvK2lOg1o076hdHdnRhivHJze/rq3uAJcmzsIQYlnI5V/Mi6MLFzumSp4dJ2Hqe+a6ey7PKeK+w4BxyGIzhV++HR3yR82PXX9tSv24eyUXF/MRYnNX+Xlsu62U1wC5Zm6L9iPdDDHuZBF1KEsX/oMUny9gpuJemWtFZHyHoRI6Rt0+asUAd/hM+0lVj2nrDxkDTeix4PNnRlWkBVvisH3URpAbMhSq+S41/oxiXvKWyc7UYmYntX5A1bPWgQkLsikjQTKwr3f0u1p
  template:
    metadata:
      name: grafana-github-oauth
      namespace: observability
    type: Opaque
