---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    access-key: AgBBqR5VMrOrtLUqMLdWf/WQQjgvi/ZITQE+JdR6ZHz8Oe2nt4OO1y6bJG35Zhw7EWEjSL6Aqr89mvFBcXDLQUZ7PpYqWeJ+KQ8gGbabn0gp6ZAHpQkzSEuEyDmOeJjZaNhGIvLTfohlDNV88Z5rRMQQt3s2PmP4Eg/UTLxMLRUKbDqIjul5/bgVmlaH0hXQk5hzXtRc+lk47h9tFFQiGhNpQxuUJqmkhGzHABxkDl8nFqkcp6xew/fpO3uNRKD7RJ8gj05RY9mKt3n8Bi03r/zfLNSHNKirRh+S7KvjagqAFuNlU5Qpcq7c7I3Bm43LnDeFArNB/f3kr0WsakuUsDpYwZPySAV7N4ALzPFRrQsJN0gYdkDfyJ9gCLatYZe9QZCAhzo53SAlXRYruiWYDa/6mb50VMt6QuNXFzcD+mdzo5bFQ4OBxA7bHUhwved0/l0w/wzXBQW5iJ0J8OR8fkWsQza7dnAH6pMDPOJxW0rER5n17T34UrB0cIhbvRGLtd2+tzllpKt8PblJxMvucQZ3mQXp5ntTZ7EH6ei5JaUfjJdEIeGxa2xzP6KbP+u1QnOEAN87Sr9X0oH78sjLBFBmT7hd0j/rCURt/iwN6YQHJ05nIMl/xn/ctGp+e9+QLU6uFBrdWESV2a13QfoZ+9q4NgVSYpu4ycIeqgiRx5TqYatip2IBrsx57ZWHAK49RebaVQHiyK0o57pHbBpCOUuqgAY1uQ==
    secret-access-key: AgAOW+UZwJxS05SlYv704xEvofNvSvxav2v6Iu6DrZkw1pWldLcybTXg1j+dO1SpXin2NKwU4ojZ1zX74alTtrFI2yz4vu8I42HWyj0Bj4ySn/BI7KmH2xFQaNyDTIFvYepxqCkOM6Vop98t/z5II8ZVSFqYzsfaAFEx1ml5m1aNBllfcAbbtxiuXVS5loncNAuioyuTK1UkitRdPFfNRb87YmladFfrFpzUNy7mFKsU61T4F1wXX1r4O9sE9O666sF7jUrFM56El7y1tdtcszkFZmkTXfvyI0lAMnqesF+yPMm9Zoxd5zRrOQixDAxrhcgbH6XG5kSKAYUlkbxVzOCyDFsI2kFDudnfjIeZX/OonE7/Q7khfmzCufK7qTxKSBoj1PemqrIzdW7WhqZnK4iZTWvZNiLasjoHFdoPyt8x+Ck82GuV6czDq39xpeRpiet4zXe4gvmX4a8YUohhgkvCD0uS9iqkwr1DufMD6nBozbxP9T97b/Suxrmk1o0Z/mlx0EharU5ESkVjgND5udcRnUCgh2YJGKl1Xp9wLGtgKxPBRsqoYdbpX+pEOwYOFCywjmoL7VvXBniTP3aeef4MOdn7SovNQ34L2dMukyvg/DEOwMqLLVDFNTLkmAD0mIhj3OeaLxzSGjWGGILlv5MY8WJczu47yBx46qFgJ16ZEv6DaxnlHOPBbAkTVFCEoSKktKm4JGcbi8jrIVuUMAjYwaXqggrYgCjYEDGdkBpppivVrQ8Fzk9d
  template:
    metadata:
      name: aws-credentials
      namespace: external-secrets
