---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proseed-route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws_access_key_id: AgB71You0SgTgXndkH7V0PefmHTcMYG0YsnvJBHNgGxWKLxmgRJk9DcBH7bVel93GnVbD6kNdmcVVAjc16WR54lcesDjnLE+mppMNOtYnNqxAPZ0X/CoLpWn5jYTsRHcvHUzhIxu8NJHjBuz3sp3Am+Th/oteby6PBM7V7PgeHyulzd59iAP4/f73jQ8hkAJ35qLAQdf7gUGrVLcfB9gNz1AKBL5ZobqncRdmQKaqZQNuNyZQYm1prhOvQ+N+5DN2U0IUzx/okMHm2JMDf/ikzfs+VnlUia+u6XSpf5tc7SO1V0kUMzsHebCftOzhMk/KqagsQa92yC8Bv73ZaiAbdtlHnGGQjtpjYenRoF2GXoD0SruO3rF+WbHJK3Ab7kcetHdQHynXdnb9E0Bod1wLwZHRIKn3JpLG1eJ3/khYfJDyfnNXu2M56M83/xEitg+aRKAReyWOczpKxT6Oqy6QPpNBCkYryzg5/RnQSITxCOWVhIpCXqIog293a1dCN+RuQduXHramCfEjnXUNprTXnzHXDExGIrDiiCY936YErjSJr/EVrA1iwIEBIZLEwLKz5trB6EvuQ/jfOThIpdEvbBDTRGGIETIuOZ2DmVJr/LdAA+1RgkYu77bqEzbhzrW/imJZFy6kWfvoH6+2IJ99E0xEy/qctc535y7fbgQnWW8PCubUE6gW6AZSuPOKXJqoxYK6zVLyTT8C3RABmRYE8E=
    aws_secret_access_key: AgAmuf1uUC439YAX0tpHsXhWOi0KSLt5L1hFzwHRzPOlv+TdN2TkNifKth98B5q/2YjRO9kBuJ7WeRegtPSmM57zyEut8rtQUnRaLI2RO3lP1k0nPbRjzCdaTrn9l9LZj3HO5XYwatrtnuixpoBFDn+8b8Q2d6VLD6ZkkJFvd+yeF1j3uSkFdqQYr5x7FlFPx58AeqOvsNsler9ZCe981H9scdU72NfhWZS4cPBtckQj0L/PxgqFsOIXaowtu/7wQ7pm3HPF1EzGfBdeb21z5DBteE4G5yOUAcR6E480dKh3YZ/Bn3zhPb/tl9Gt74sZha1jbfiFjzzhgqXipvOPiGylZnq12bekEnvblPMtCt4JDqAfHhYy+aNztZEIyF6bSv8IU4Qw/HREUMsxWz1nHCyZezw9nE2sPbyLmynUV6VDJ+YvwnCG2n+oYGxcFw3EPbAYajc0HksFw0cCSKOLUXfgZA1qumT6FePuFOYIQYlANBrSLBbqDht95beTDhELR7kbQMelB1RejjwSQj+YgVUrjUU6bje1sfPjW3JP9iOAB3N4X/6RlNVQB2vjAh74IXHI96XyYQVKJZIUpoxLy1FiCcB1HUpK+4KrYf9H1Sw0tc4lrM6tm+JcKkW9Mfyh15hUswOhibCgAbQvSs/77KSnUlamcNAcG6fiI3MZ/TwG3co91BEqE5g2KSxcFANt3/y40JEHAQhvkaOWBIAOEhlBKGll6op4ci6qSjsNeFk=
  template:
    metadata:
      name: proseed-route53-credentials
      namespace: cert-manager
    type: Opaque
