# OpenTelemetry Operator Helm Chart Values
# https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib

# cert-manager가 이미 설치되어 있다고 가정
admissionWebhooks:
  certManager:
    enabled: true
