apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin-user.yaml
  - github-app-repo-creds.yaml
  - ingress.yaml
  - namespace.yaml
  - notifications-secret.yaml
  - notifications.yaml
  - clusters/lab.yaml
