apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: 0.102.0
      helm:
        valueFiles:
          - $lab/k8s/observability/otel-operator/values.yaml
    - repoURL: https://github.com/skkuding/lab
      targetRevision: main
      ref: lab
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true